export { default as Home } from './mainLayout/Home'
export { default as Search } from './mainLayout/Search'
export { default as Explore } from './mainLayout/Explore'
export { default as Trending } from './mainLayout/Trending'
export { default as Personalize } from './fullLayout/Personalize'
export { default as Navbar } from './Navbar'
export { default as PlayerControls } from './media/Player'
export { default as Artist } from './Artist'
export { default as Album } from './Album'
export { default as Song } from './Song'
export {default as Favorite} from './mainLayout/Favorite'
export {default as Recommended} from './mainLayout/Recommended'
export { default as Login } from './fullLayout/Login'
export { default as SignUp } from './fullLayout/SignUp'